name: check_in_pro_for_visitor
description: A new Flutter application.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 2.3.0+345

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  rxdart: ^0.24.0
  flutter_secure_storage: ^3.3.3
  fluttertoast: ^7.1.6
  blurrycontainer: ^0.0.1
  rounded_loading_button: ^1.0.8
  flutter_inappwebview: ^4.0.0+4
  image: ^2.1.12
  exif: ^1.0.2
  data_connection_checker: ^0.3.4
  shared_preferences: ^0.5.6+2
  barcode_scan: ^3.0.0
  chopper: ^2.4.2
  provider: ^3.0.0+1
  connectivity: ^0.4.3+2
  http: ^0.12.0+4
  json_annotation:
  autocomplete_textfield: ^1.7.3
  permission_handler: ^3.2.2
  assorted_layout_widgets: ^1.3.6
#  camera_fix_exception:
  # camera:
  camera:
    git:
      url: https://github.com/checkinpro/camera_flutter.git
      ref: master
  path_provider:
  signalr_client: ^0.1.6
  async: ^2.4.0
  get_it: ^4.0.0
  wakelock: ^0.1.4+2
  flutter_image_compress: ^0.6.5+1
  flutter_exif_rotation: ^0.2.7
  native_device_orientation: ^0.3.0
  flutter_isolate: ^1.0.0+11
  simple_animations: ^2.2.1
  flare_flutter: ^2.0.3
  flutter_rating_bar: ^3.0.1+1
  device_info: ^0.4.2+1
  keyboard_avoider: ^0.1.2
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  package_info: ^0.4.0+3
  get_ip: ^0.4.0
  app_settings: 4.0.4
  keyboard_visibility: ^0.5.2
  firebase_messaging: ^6.0.13
  auto_size_text: ^2.1.0
  qr_flutter: ^3.2.0
  flutter_widget_from_html: ^0.4.1
  flutter_widget_from_html_core: ^0.4.1
  hand_signature: ^0.6.1+3
  flutter_html_to_pdf: ^0.5.2
  flutter_full_pdf_viewer: ^1.0.6
  moor: ^3.1.0
  moor_ffi: ^0.5.0
  path: ^1.6.4
  uuid: ^2.1.0
  giffy_dialog: ^1.7.0
  intl: ^0.16.1
  esc_pos_printer: ^3.1.6
  wifi: ^0.1.5
  ping_discover_network: ^0.2.0+1
  esc_pos_utils: ^0.4.0
  #esc_pos_bluetooth: ^0.2.8
  flutter_map: ^0.8.2
  flip_panel: ^1.0.1
  firebase_ml_vision: ^0.9.4
  tiengviet: ^0.3.0
  flutter_native_image: ^0.0.5
  flutter_staggered_grid_view: ^0.3.2
  flutter_widgets: ^0.1.12
  assets_audio_player: ^2.0.13
  flutter_html: ^1.0.0
  flutter_colorpicker: ^0.3.5
  smooth_page_indicator: ^0.2.3
  dots_indicator: ^1.2.0
  # device_simulator: ^0.9.6
  checkbox_grouped:
    git:
      url: https://github.com/checkinpro/checkbox_grouped.git
      ref: main
  carousel_slider:
    git:
      url: https://github.com/checkinpro/carousel_slider.git
      ref: main
  im_stepper:
    git:
      url: https://github.com/checkinpro/cip_stepper.git
      ref: main
  qr_code_scanner:
    git:
      url: https://github.com/checkinpro/qr_code_scanner.git
      ref: master
  escposprinter:
    git:
      url: https://github.com/marcusfelix/esc-pos-printer-flutter.git
      ref: master

dev_dependencies:
  moor_generator: ^3.1.0
  flutter_test:
    sdk: flutter
  chopper_generator:
  build_resolvers: ^1.3.10
  built_value_generator:
  json_serializable:
  analyzer: ^0.39.14

  # No version number means the latest version
  build_runner: ^1.10.1

  gen_lang: 0.1.0
  lang_table: 0.2.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/lang/
    - assets/flare/
    - assets/audios/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Eraser-Regular
      fonts:
        - asset: assets/fonts/Eraser-Regular.ttf
    - family: Led
      fonts:
        - asset: assets/fonts/Led.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Light.ttf
          weight: 300
        - asset: assets/fonts/Montserrat-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/Montserrat-Bold.ttf
          weight: 700
    - family: OpenSans
      fonts:
        - asset: assets/fonts/OpenSans-Regular.ttf
          weight: 300
        - asset: assets/fonts/OpenSans-SemiBold.ttf
          weight: 500
        - asset: assets/fonts/OpenSans-Bold.ttf
          weight: 700

  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages